### root domain test
GET http://localhost:8000/

###### admin API ######
### GET ADMIN API
GET http://localhost:8000/api/v1/admin

### POST ADMIN API
POST  http://localhost:8000/api/v1/admin
Content-Type: application/json

{
    "fName" : "admin",
    "lName" : "admin",
    "email" : "c@admin.com",
    "phone" : "1234567890",
    "address" : "SYDNEY",
    "dob" : "2020-02-20",
    "password" : "admin"
}

### POST ADMIN EMAIL VERIFICATION API
POST  http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email" : "c@admin.com",
   "emailValidationCode" : "82753135-c105-4362-a844-8d22f47a0a11"
}

### GET ADMIN API
PATCH http://localhost:8000/api/v1/admin