### root domain test
GET http://localhost:8000/

###### admin API ######
### GET ADMIN API
GET http://localhost:8000/api/v1/admin

### POST ADMIN API
POST  http://localhost:8000/api/v1/admin
Content-Type: application/json

{
    "fName" : "admin",
    "lName" : "admin",
    "email" : "a@admin.com",
    "phone" : "1234567890",
    "address" : "SYDNEY",
    "dob" : "2020-02-20",
    "password" : "admin"
}

### POST ADMIN EMAIL VERIFICATION API
POST  http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email" : "a@admin.com",
   "emailValidationCode" : "95244771-cf94-4893-836d-29070b554d71"
}

### LOGIN API
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
    "email" : "sam@email.com",
    "password" : "123456"
}